Repository BulletBoxProject/BE-project, pull requests merged in 2023-02, with the labels that each got.

#201 🐛 Fix: cd 오류 수정
  .github/workflows/ci-cd.yml
Labels: bug

#202 🐛 Fix: cd 파일 수정
  .github/workflows/ci-cd.yml
Labels: bug

#203 🐛 Fix: cd 수정
  .github/workflows/ci-cd.yml
Labels: bug

#204 🐛 Fix: docker-compose 파일 문법 수정
  docker-compose.yml
Labels: bug

#205 🐛 Fix: docker-compose 파일 수정
  docker-compose.yml
Labels: bug

#206 🐛 Fix: docker-compose 파일 수정 및 redis host 수정
  docker-compose.yml
  src/main/resources/application.properties
Labels: bug

#207 🐛 Fix: redis host 변경
  src/main/resources/application.properties
Labels: bug

#211 🐛 Fix: cd, docker-compose 파일 수정
  .github/workflows/ci-cd.yml
  src/main/resources/application.properties
Labels: bug

#210 ✨ feat: 불렛 이름 추가
  src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
Labels: feature

#191 ✨ Feat : 카카오 OAuth 구현
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
  src/main/java/com/hanghae/bulletbox/member/type/SocialTypeEnum.java
  src/main/resources/application.properties
Labels: feature

#212 🐛 Fix: application.properties 수정
  src/main/resources/application.properties
Labels: bug

#213 🐛 Fix: application.properties 수정
  src/main/resources/application.properties
Labels: bug

#215 ♻️ Refactor: 개행 추가
  .github/workflows/ci-cd.yml
Labels: refactor

#216 🐛 Fix: properties 파일 수정
  src/main/resources/application.properties
Labels: bug

#217 ♻️ Refactor: properties 수정(버그 해결 완료)
  src/main/resources/application.properties
Labels: refactor

#218 ♻️ refactor: Category 도메인에 있는 모든 API 리팩토링
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCreateCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseShowCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/entity/Category.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
Labels: refactor

#222 ✨ Feat : Test용 로그인 구현
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: feature

#221 🐛 fix: 카테고리 삭제 시 해당 카테고리를 사용하던 Todo와 favorite의 카테고리 값들 null로 변경
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: fix

#224 ✨ Feat : 첫번째 로그인 여부 확인 로직 추가
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/ResponseLoginDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: feature

#226 🐛 fix: 회원가입 시 발생하는 500에러 수정
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
Labels: fix

#228 ✨ feat: 일기장 수정, 삭제 시 그 달의 emotion 리스트로 반환하도록 변경
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
Labels: feature

#230 🐛 Fix : 체험하기 로그인 non null key required 오류 수정
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: bug

#232 🐛 Fix: 카카오 로그인 시, KOE 303 에러 수정
  scripts/deploy.sh
Labels: bug

#234 ✨ Feat : 카카오, 구글 OAuth 첫번째 로그인 여부 확인 로직 추가
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
Labels: feature

#236 🐛 Fix : 첫번째 로그인 true/false 수정
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
Labels: fix

#238 🐛 Fix : 카카오 구글 OAuth setFirstLogin로직 추가
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
Labels: fix

#240 🐛 fix: 할 일 수정 시 time 수정내용 반영
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
Labels: fix

#242 ✨ feat: 루틴 생성 시 카테고리 정보 반환하는 로직 추가
  src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseCreateFavoriteTodoDto.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
Labels: feature

#244 ♻️ Refactor: 시큐리티 적용
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/exception/JwtExceptionHandlerFilter.java
Labels: refactor

#246 🐛 fix: Security config에서 members get 요청 열어줌
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: fix

#247 🐛 fix: Oauth properties 값 수정
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: fix

#248 🐛 fix: Oauth properties 값 수정
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: fix

#250 🐛 Fix: 구글 로그인 RestTemplate 이슈 수정
  build.gradle
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
Labels: fix

#256 🐛 fix: Todo 업데이트 메소드 수정
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
Labels: fix

#258 ✨ feat: Security config에 프론트 배포 주소 추가
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: feature

#259 ♻️ Refactor: 루틴 수정 시, 응답 값 출력하도록 수정
  .github/workflows/ci-cd.yml
  scripts/deploy.sh
  src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseUpdateFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
  src/main/resources/application.properties
Labels: refactor

#261 🐛 Fix: docker compose redis 수정
  .github/workflows/ci-cd.yml
  scripts/deploy.sh
  src/main/resources/application.properties
Labels: bug

#263 🐛 fix: Security config에 프론트 배포 주소 추가
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: fix

#264 🐛 Fix: 스웨거 path 수정
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: bug

#266 🐛 fix: 메인 페이지 조회 시 첫 로그인 여부 반환
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowMainPageDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
Labels: fix

#267 ♻️ Refactorr: TodoBullet Enum 의 Name 값을 응답하도록 로직 수정
  src/main/java/com/hanghae/bulletbox/todo/dto/SearchTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
Labels: refactor

#269 ♻️ Refactor: 루틴 생성 시, 삭제된 MemoId 값을 응답하지 않도록 수정
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
Labels: refactor

#273 ♻️ Refactor: 리드미 개행 추가(푸시 테스트)
  README.md
Labels: refactor

#275 ✨ Feat: Nginx + Docker 를 활용한 무중단 배포 테스트
  .github/workflows/ci-cd.yml
  docker-compose.blue.yml
  docker-compose.green.yml
  scripts/deploy.sh
Labels: feature

#276 🐛 Fix: 무중단 배포 테스트 실패로 원래 설정으로 변경
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
  scripts/deploy.sh
Labels: fix

#278 🐛 Fix: 배포 스크립트 실행 시, 도커 컴포즈로 실행된 모든 컨테이너가 종료되지 않는 현상 발생
  scripts/deploy.sh
Labels: bug

#283 🐛 Fix: 카테고리 수정 시, 카테고리의 색상만 변경될 경우 실패하는 오류 발생
  src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
Labels: bug

#285 🐛 Fix: 배포 스크립트가 정상 작동이 안 되는 오류 발생
  appspec.yml
Labels: bug

#287 🐛 Fix: 배포 스크립트 위치 수정
  appspec.yml
  deploy.sh
Labels: bug

#288 🐛 Fix: ci-cd 코드 원상 복구
  .github/workflows/ci-cd.yml
  scripts/deploy.sh
Labels: bug

#289 🐛 Fix: github actions ci-cd 파일 수정
  .github/workflows/ci-cd.yml
Labels: bug

#291 🐛 Fix: 카테고리 생성 시, 생성이 안 되는 오류 수정
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
Labels: bug

#293 🔧 Chore: 프로젝트 패키지 재구조화
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
  src/main/java/com/hanghae/bulletbox/daily/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/daily/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/RequestCreateTodoDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/RequestLoadFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/RequestUpdateTodoDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/ResponseDailyDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/ResponseLoadFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/ResponseShowTodoCreatePageDto.java
  src/main/java/com/hanghae/bulletbox/daily/dto/ResponseTodoUpdatePageDto.java
  src/main/java/com/hanghae/bulletbox/daily/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/daily/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/main/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/main/dto/CalendarDto.java
  src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowCalendarDto.java
  src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowDailyByCategoryDto.java
  src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowMainPageDto.java
  src/main/java/com/hanghae/bulletbox/main/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
Labels: chore

#296 🐛 Fix: 루틴 수정 시, 요청 온 루틴의 메모 ID 와 응답한 루틴의 메모 ID 불일치한 오류 해결
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteMemoDto.java
Labels: bug

#297 ♻️ refactor: Member 도메인 리팩토링
  src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
  src/main/java/com/hanghae/bulletbox/main/service/MainService.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/repository/MemberRepository.java
  src/main/java/com/hanghae/bulletbox/member/service/AuthService.java
  src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
  src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
  src/main/java/com/hanghae/bulletbox/member/service/MailService.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: refactor

#299 🐛 fix: 로그인 시 비밀번호 검증 오류 해결
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/repository/MemberRepository.java
  src/main/java/com/hanghae/bulletbox/member/service/AuthService.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: fix

#302 ♻️ Refactor: Daily 컨트롤러, 서비스에 대한 파사드 패턴 리팩토링
  src/main/java/com/hanghae/bulletbox/daily/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/daily/service/DailyFacade.java
  src/main/java/com/hanghae/bulletbox/daily/service/DailyFacadeImpl.java
  src/main/java/com/hanghae/bulletbox/daily/service/DailyService.java
Labels: refactor
