Repository BulletBoxProject/BE-project, pull requests merged in 2023-01, with the labels that each got.

#4 🐛 Fix: 패키지 경로 재설정 및 시큐리티 의존성 주입
  build.gradle
  src/main/java/com/hanghae/bulletbox/common/security/UserDetailsServiceImpl.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
Labels: bug

#7 ✨ Feat: Response 설정
  src/main/java/com/hanghae/bulletbox/common/response/Response.java
Labels: feature

#12 📝 doc: git actions CI 적용
  .github/workflows/ci.yml
Labels: documentation

#13 📝 doc: git actions에 필요한 내용 추가
  .github/workflows/ci.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: documentation

#10 ✨ Feat : 로그인 API 구현
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/LoginDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
  src/main/java/com/hanghae/bulletbox/member/mapper/MemberMapper.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: feature

#16 ♻️ Refactor : 회원가입, 로그인 API 수정
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/LoginDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/SignupDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/mapper/MemberMapper.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: refactor

#19 📝 docs: CD 적용
  .github/workflows/ci-cd.yml
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: documentation

#20 ✨ Feat: 메인 페이지 조회 API 구현
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/entity/Category.java
  src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/CalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseMainDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
  src/main/java/com/hanghae/bulletbox/todo/repository/MemoRepository.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: feature

#22 🐛 fix: Codedeploy용 scipts 파일 수정
  scripts/start.sh
  scripts/stop.sh
Labels: fix

#25 ✨ feat: 메일 인증에 필요한 secret 내용 CI/CD에 포함
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
Labels: documentation

#23 ✨ Feat : 이메일인증 구현
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/hanghae/bulletbox/common/config/MailConfig.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/VerifyCodeDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/MailService.java
Labels: feature

#29 🔧 chore: MySQL RDS 연결
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/resources/application.properties
Labels: feature

#34 🐛 fix: Security config 수정
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: fix

#30 ✨ Feat: 메인 페이지 내 달력 조회 날짜 변경 API 구현
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseChangeCalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: feature

#35 ♻️ Refactor : 패스워드 정규식 수정 및 localhost 수정
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
Labels: refactor

#38 ♻️ Refactor: 메인 페이지 조회 시, 달력의 날짜를 현재 연, 월로 설정
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: refactor

#39 🔧 Chore: 사용하지 않는 import 삭제
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: refactor

#47 ✨ Feat: TodoDto 생성
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
Labels: feature

#49 ♻️ Refactor: TodoDto Builder 패턴 private 적용
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
Labels: refactor

#50 ✨ Feat : Daily 로그 조회 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Memo.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: feature

#52 ✨ Feat: 데일리 로그 조회 날짜 변경 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: feature

#54 ✨ Feat : 데일리 로그 카테고리 별 조회 API 구현
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: feature

#55 ✨ Feat: 메인 페이지 카테고리별 데일리 로그 조회 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyByCategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: feature

#57 ♻️ Refactor : 이메일 인증 controller 로직 수정
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: refactor

#60 ♻️ Refactor: 메인 페이지 조회 API 수정
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseMainDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowMainPageDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
Labels: refactor

#63 ♻️ Refactor : 데일리 로그 카테고리별 조회 API 수정
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: refactor

#64 ♻️ Refactor: 메인 페이지 API 수정
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowCalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyByCategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
Labels: refactor

#65 ✨ Feat : 데일리로그 조회 날짜 변경 API구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: feature

#66 ♻️ Refactor : 이메일인증 예외처리 refactor
  src/main/java/com/hanghae/bulletbox/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanghae/bulletbox/common/response/Response.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: refactor

#67 ♻️ Refactor : equals 변수 순서 변경
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Labels: refactor

#73 ✨ Feat: Swagger 적용
  build.gradle
  src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
  src/main/java/com/hanghae/bulletbox/common/response/Response.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/CalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowCalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyByCategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowMainPageDto.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/VerifyCodeDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/resources/application.properties
Labels: feature

#76 🐛 Fix: SwaggerConfig ApiKey의 name, keyname 값이 매칭되지 않는 에러
  src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
Labels: bug

#84 ✨ Feat: 카테고리 목록 조회 API 구현
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseShowCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
Labels: feature

#77 ✨ Feat : 자주 쓰는 할일, 자주 쓰는 할일 메모 Entity 추가
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteMemoRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
Labels: feature

#85 ✨ Feat: 카테고리 생성 API 구현
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/RequestCreateCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/entity/Category.java
  src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
Labels: feature

#87 ✨ feat: 데일리 로그 할일 추가 페이지 조회 API 구현
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowTodoCreatePageDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/todo/MemoBullet.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoMemoRepository.java
Labels: feature

#88 ✨ Feat: 특정 카테고리 수정 API 구현
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/RequestUpdateCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/entity/Category.java
  src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
Labels: feature

#89 ✨ Feat: 특정 카테고리 API 삭제 구현
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseDeleteCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
Labels: feature

#91 ♻️ Refactor: 카테고리 생성 API 수정
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCreateCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
Labels: refactor

#93 ♻️ Refactor: 전체 코드 리팩토링
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
Labels: refactor

#95 ✨ Feat : SecurityConfig 프론트 도메인 추가
  src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Labels: feature

#97 ✨ Feat: 마이 페이지 조회 API 구현
  src/main/java/com/hanghae/bulletbox/mypage/controller/MyPageController.java
  src/main/java/com/hanghae/bulletbox/mypage/dto/MyPageDto.java
  src/main/java/com/hanghae/bulletbox/mypage/dto/ResponseShowMyPageDto.java
  src/main/java/com/hanghae/bulletbox/mypage/service/MyPageService.java
Labels: feature

#99 ✨ feat: 할 일 추가 API 구현
  src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/RequestCreateTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
  src/main/java/com/hanghae/bulletbox/member/entity/Member.java
  src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: feature

#101 🐛 fix: 메인페이지 조회 시 오류 수정
  src/main/java/com/hanghae/bulletbox/common/entity/TimeStamped.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
Labels: fix

#103 🐛 Fix: 메인 페이지 조회 시 오류 발생
  src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoMemoRepository.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Labels: bug

#105 🐛 Fix: 메인 페이지 조회 시 달력 내 할 일의 요일과 개수가 출력되지 않는 오류 발생
  src/main/java/com/hanghae/bulletbox/BulletBoxApplication.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowCalendarDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: bug

#108 🐛 Fix: LocalDateTime 사용 시, UTC로 적용되는 오류 수정
  src/main/java/com/hanghae/bulletbox/BulletBoxApplication.java
  src/main/java/com/hanghae/bulletbox/common/entity/TimeStamped.java
Labels: bug

#109 🐛 fix: 할 일 저장시 null값 메모가 저장되는 오류 수정
  src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: fix

#112 🐛 Fix: 메인 페이지 조회 시 카테고리 색상이 null인 오류
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: bug

#110 ✨ feat: 할일 삭제 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoMemoRepository.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: feature

#115 🐛 fix: 할 일 작성할 때 카테고리가 없으면 나오던 오류 수정
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: fix

#120 ✨ Feat : Redis 적용
  build.gradle
  src/main/java/com/hanghae/bulletbox/common/config/MailConfig.java
  src/main/java/com/hanghae/bulletbox/common/config/RedisConfig.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/common/redis/RedisUtil.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/service/MailService.java
  src/main/resources/application.properties
Labels: feature

#121 ✨ Feat: 자주 쓰는 할 일 생성 API 구현
  src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteMemoDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/RequestCreateFavoriteTodoDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseCreateFavoriteTodoDto.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
Labels: feature

#122 ✨ feat: 데일리로그 수정 페이지 조회 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseTodoUpdatePageDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
Labels: feature

#124 ♻️ Refactor: Transactional 어노테이션 붙이기
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
Labels: refactor

#130 🐛 fix: 데일리 로그 조회 로직 수정
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: fix

#135 fix: 데일리 로그 조회 시 categoryColor가 출력되지 않는 오류 수정
  src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
Labels: fix

#137 🐛 fix: 메인 페이지 조회 시 오류 수정
  src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
Labels: fix

#138 ✨ Feat: 자주 쓰는 할 일 삭제 API 구현
  src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteMemoRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
Labels: feature

#139 ✨ feat: 데일리 로그 할 일 수정 API 구현
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/RequestUpdateTodoDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: feature

#141 ✨ Feat: 루틴 수정 API 로직 구현
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
  src/main/java/com/hanghae/bulletbox/favorite/dto/RequestUpdateFavoriteTodoDto.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteMemoRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
Labels: feature

#142 🐛 Fix: LocalDateTime KST 설정
  src/main/java/com/hanghae/bulletbox/BulletBoxApplication.java
Labels: bug

#143 ✨ feat: 데일리 로그에서 루틴 불러오기 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/RequestLoadFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
Labels: feature

#146 ✨ Feat: 할 일 검색 API 구현
  src/main/java/com/hanghae/bulletbox/todo/controller/TodoController.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseSearchTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/SearchPageDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/SearchTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
  src/main/java/com/hanghae/bulletbox/todo/service/SearchTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: feature

#148 ✨ feat: 할 일 수정 페이지 조회 시 categoryColor 값 추가
  src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
Labels: feature

#144 ✨ Feat : RefreshToken 구현
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
  src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
  src/main/java/com/hanghae/bulletbox/member/dto/VerifyCodeDto.java
  src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Labels: feature

#154 ✨ feat: Diary Entity 생성 및 패키지 구조 변경
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
  src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
  src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
  src/main/java/com/hanghae/bulletbox/todo/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/todo/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/todo/dto/CalendarDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/DailyTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/RequestCreateTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/RequestLoadFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/RequestUpdateTodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseDailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowCalendarDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyByCategoryDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowMainPageDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowTodoCreatePageDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseTodoUpdatePageDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/todo/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
Labels: feature

#156 🐛 Fix: 루틴 불러오기 API 호출 시, 발생하는 오류 수정
  src/main/java/com/hanghae/bulletbox/todo/service/DailyTodoService.java
Labels: bug

#157 ✨ feat: 일기장 페이지 조회 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/MonthlyEmotionDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryPageDto.java
  src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
  src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: feature

#159 🐛 Fix: 할 일 API 호출 시, 오류 발생 해결
  src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: bug

#161 🐛 Fix: 루틴 수정 시, 발생하는 오류 해결
  src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
Labels: bug

#162 ✨ feat: 일기장 페이지 달력 조회 날짜 변경 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryCalendarPageDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryPageDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: feature

#164 🐛 Fix: 배포 스크립트 수정
  scripts/start.sh
  scripts/stop.sh
Labels: fix

#165 🐛 Fix: 배포 스크립트 수정
  scripts/start.sh
Labels: fix

#166 ✨ feat: 일기 조회 날짜 변경 API 구현
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
  src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: feature

#167 🐛 Fix: 배포 스크립트 테스트
  appspec.yml
  scripts/start.sh
Labels: fix

#168 🐛 Fix: 배포 스크립트 테스트
  appspec.yml
  scripts/start.sh
Labels: fix

#169 ✨ feat: 일기장 생성 및 수정 API 구현
  src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
  src/main/java/com/hanghae/bulletbox/diary/dto/RequestDiaryUpdateDto.java
  src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: feature

#170 🐛 Fix: 배포 스크립트 테스트
  scripts/start.sh
Labels: fix

#172 ♻️ Refactor: 배포 스크립트 적용 완료로 인한 불필요한 코드, 파일 제거
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: refactor

#174 ✨ feat: 루틴 불러오기 시 저장된 todo 응답 값으로 추가
  src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseLoadFavoriteDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/DailyTodoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
Labels: feature

#176 ✨ feat: 데일리 로그 날짜 변경 조회 시 응답값에 카테고리 추가
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
Labels: feature

#179 ✨ feat: 일기장 작성/수정 시 해당 내용 반환하는 로직 추가
  src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: feature

#182 🐛 Fix: 배포 스크립트 수정
  scripts/deploy.sh
Labels: bug

#183 🐛 Fix: 배포 스크립트 수정
  appspec.yml
Labels: bug

#184 🐛 Fix: docker image name 소문자로 변경
  scripts/deploy.sh
Labels: bug

#185 🐛 Fix: dockerfile, ci 파일 수정
  .github/workflows/ci.yml
  Dockerfile
Labels: bug

#186 🐛 Fix: 도커 배포 테스트
  .github/workflows/ci.yml
  Dockerfile
  scripts/deploy.sh
Labels: bug

#187 🐛 Fix: docker 배포 테스트
  scripts/deploy.sh
Labels: bug

#189 ♻️ Refactor: 도커 적용 완료로 인한 불필요한 코드 제거
  appspec.yml
  scripts/deploy.sh
Labels: refactor

#194 ♻️ refactor: Todo 도메인에 속한 모든 API 리팩토링 진행
  src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
  src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
  src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
  src/main/java/com/hanghae/bulletbox/todo/controller/DailyController.java
  src/main/java/com/hanghae/bulletbox/todo/controller/MainController.java
  src/main/java/com/hanghae/bulletbox/todo/dto/CalendarDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/DailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/dto/ResponseDailyDto.java
  src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
  src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
  src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Labels: refactor

#197 🐛 fix: 일기장이 없는 날짜 조회 시 발생하던 오류 수정
  src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
  src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
Labels: fix

#195 ✨ Feat: docker-compose 테스트
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  docker-compose.yml
  scripts/deploy.sh
Labels: feature

#198 🐛 Fix: merge 시, cd 오류 발생
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
Labels: bug

#199 🐛 Fix: CD 오류 수정
  .github/workflows/ci-cd.yml
Labels: bug

#200 🐛 Fix: cd uses or run key 에러 수정
  .github/workflows/ci-cd.yml
Labels: bug
